<a href="https://colab.research.google.com/github/SAMMY-4870/Deep_Learning/blob/main/samarth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
# Row vector
vector = np.array([1, 2, 3, 4, 5])
print("Vector:", vector)


Vector: [1 2 3 4 5]


In [ ]:
# Q2 Find unit vector choice
import numpy as np


v = np.array([2, -3, 6])

# Step 3: Calculate the magnitude (length) of the vector
magnitude = np.linalg.norm(v)

# Step 4: Calculate the unit vector
unit_vector = v / magnitude

# Step 5: Print everything
print("Original vector:", v)
print("Magnitude:", magnitude)
print("Unit vector:", unit_vector)


Original vector: [ 2 -3  6]
Magnitude: 7.0
Unit vector: [ 0.28571429 -0.42857143  0.85714286]


In [ ]:
# Q3 Find the dot product of 2 vector


# Define two vectors of the same length
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate the dot product
dot_product = np.dot(a, b)

# Print the result
print("Vector a:", a)
print("Vector b:", b)
print("Dot Product:", dot_product)


Vector a: [1 2 3]
Vector b: [4 5 6]
Dot Product: 32


In [ ]:
#2 matrix multiplication 3*3 Matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Step 2: Matrix multiplication
C = np.dot(A, B)

# Step 3: Print the result
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A × B =\n", C)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
A × B =
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#Q5 Implement a single neural system with reulu  OUTPUT MAX(0,2)

x = np.array([1, 1])
w = np.array([1, 1])
b = 0

z = np.dot(w, x) + b
relu_output = max(0, z)

print("Linear Output (z):", z)
print("ReLU Output:", relu_output)


Linear Output (z): 2
ReLU Output: 2
